"""Import ml.features without the pickled transformers produced by the notebooks.

The real TF-IDF / SVD / normalizer are generated by notebooks/model_training.ipynb
and are not committed, so tests replace joblib.load with shape-correct stand-ins.
"""

import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def _fake_transformer(n_out):
    t = MagicMock()
    t.transform.side_effect = lambda x: np.zeros((1 if not hasattr(x, "shape") else x.shape[0], n_out))
    return t


@pytest.fixture(scope="session")
def features_module():
    fakes = {
        "tfidf_vectorizer.pkl": _fake_transformer(500),
        "svd_reducer.pkl": _fake_transformer(100),
        "normalizer.pkl": _fake_transformer(100),
    }
    with patch("joblib.load", side_effect=lambda path: fakes[Path(path).name]):
        sys.modules.pop("ml.features", None)
        import ml.features as features
    return features
